name: Build binaries for moe-sticker-bot and msbimport

on: push

jobs:
  build_msb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - name: Build MSB CLI
        run: |
          go version
          GOOS=linux GOARCH=amd64 go build -o moe-sticker-bot_linux_amd64 cmd/moe-sticker-bot/main.go
          GOOS=linux GOARCH=arm64 go build -o moe-sticker-bot_linux_aarch64 cmd/moe-sticker-bot/main.go
          GOOS=windows GOARCH=amd64 go build -o moe-sticker-bot_windows_amd64.exe cmd/moe-sticker-bot/main.go
          GOOS=windows GOARCH=arm64 go build -o moe-sticker-bot_windows_aarch64.exe cmd/moe-sticker-bot/main.go
          GOOS=darwin GOARCH=amd64 go build -o moe-sticker-bot_macos_amd64 cmd/moe-sticker-bot/main.go
          GOOS=darwin GOARCH=arm64 go build -o moe-sticker-bot_macos_aarch64 cmd/moe-sticker-bot/main.go

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: msb_bins
          path: moe-sticker-bot*

  build_msbimport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - name: Build Msbimport CLI
        run: |
          go version
          GOOS=linux GOARCH=amd64 go build -o msbimport_linux_amd64 cmd/msbimport/main.go
          GOOS=linux GOARCH=arm64 go build -o msbimport_linux_aarch64 cmd/msbimport/main.go
          GOOS=windows GOARCH=amd64 go build -o msbimport_windows_amd64.exe cmd/msbimport/main.go
          GOOS=windows GOARCH=arm64 go build -o msbimport_windows_aarch64.exe cmd/msbimport/main.go
          GOOS=darwin GOARCH=amd64 go build -o msbimport_macos_amd64 cmd/msbimport/main.go
          GOOS=darwin GOARCH=arm64 go build -o msbimport_macos_aarch64 cmd/msbimport/main.go

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: msbimport_bins
          path: msbimport*

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ build_msb, build_msbimport ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: releases/

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          # append_body: true
          body_path: ".github/workflows/release_note.md"
          files: |
            releases/*/*
