name: Build nginx for @moe-sticker-bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build nginx container amd64
        run: |
          bash .github/workflows/msb_nginx_amd64.sh ${{ secrets.GITHUB_TOKEN }}

  build_aarch64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build nginx container aarch64
        run: |
          bash .github/workflows/msb_nginx_aarch64.sh ${{ secrets.GITHUB_TOKEN }}

